# Generated by Django 4.2.5 on 2023-09-27 18:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.CharField()),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('pet_more_info_url', models.CharField()),
                ('pet_picture_url', models.CharField(blank=True, null=True)),
                ('city', models.CharField(null=True)),
                ('state', models.CharField(null=True)),
                ('users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
            ],
        ),
    ]
