# Generated by Django 4.2.5 on 2023-10-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_pet_contact_pet_gender_pet_primary_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='spayed_neutered',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
