# Generated by Django 4.2.5 on 2023-10-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_pet_id_alter_pet_pet_id_alter_pet_spayed_neutered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
