# Generated by Django 4.2.5 on 2023-10-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_pet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='id',
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
